version: "3"

tasks:
  # フロントエンドビルド
  build:frontend:
    desc: フロントエンドをビルド
    dir: web
    cmds:
      - echo "フロントエンドをビルド中..."
      - bun run build
      - echo "フロントエンドビルド完了 → dist/public/"

  # バックエンドビルド
  build:backend:
    desc: バックエンドをビルド
    dir: cmd/twitch-fax
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
      COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
      BUILD_TIME:
        sh: date -u '+%Y-%m-%d %H:%M:%S UTC'
    cmds:
      - echo "バックエンドをビルド中..."
      - |
        go build -ldflags "\
          -X 'github.com/nantokaworks/twitch-fax/internal/version.Version={{.VERSION}}' \
          -X 'github.com/nantokaworks/twitch-fax/internal/version.Commit={{.COMMIT}}' \
          -X 'github.com/nantokaworks/twitch-fax/internal/version.BuildTime={{.BUILD_TIME}}'" \
          -o ../../dist/twitch-fax .
      - echo "バックエンドビルド完了 → dist/twitch-fax"
      - |
        if [ -f .env ]; then
          cp .env ../../dist/.env
          echo ".envファイルをコピーしました → dist/.env"
        fi
      - |
        # dist/local.dbが既に存在する場合は上書きしない
        if [ -f ../../dist/local.db ]; then
          echo "local.dbファイルは既に存在します → dist/local.db (上書きしません)"
        elif [ -f local.db ]; then
          cp local.db ../../dist/local.db
          echo "local.dbファイルをコピーしました → dist/local.db"
        fi

  # find-faxツールビルド
  build:find-fax:
    desc: find-faxツールをビルド
    dir: cmd/find-fax
    cmds:
      - echo "find-faxをビルド中..."
      - go build -o ../../dist/find-fax .
      - echo "find-faxビルド完了 → dist/find-fax"

  # 統合ビルド
  build:all:
    desc: フロントエンドとバックエンドを両方ビルド
    cmds:
      - task: clean
      - task: build:frontend
      - task: build:backend
      - task: build:find-fax
      - echo "全ビルド完了！"
      - echo "実行 → ./dist/twitch-fax"

  # クリーンアップ
  clean:
    desc: ビルドファイルをクリーンアップ
    cmds:
      - echo "ビルドファイルをクリーンアップ中..."
      - |
        # local.dbを一時的に退避
        if [ -f dist/local.db ]; then
          echo "local.dbを退避中..."
          mv dist/local.db /tmp/twitch-fax-local.db.tmp
        fi
      - |
        # .envファイルも退避
        if [ -f dist/.env ]; then
          echo ".envを退避中..."
          mv dist/.env /tmp/twitch-fax-env.tmp
        fi
      - rm -rf dist
      - rm -rf web/dist
      - mkdir -p dist
      - |
        # local.dbを復元
        if [ -f /tmp/twitch-fax-local.db.tmp ]; then
          echo "local.dbを復元中..."
          mv /tmp/twitch-fax-local.db.tmp dist/local.db
        fi
      - |
        # .envを復元
        if [ -f /tmp/twitch-fax-env.tmp ]; then
          echo ".envを復元中..."
          mv /tmp/twitch-fax-env.tmp dist/.env
        fi
      - echo "クリーンアップ完了"

  # 開発サーバー起動（フロントエンド）
  dev:frontend:
    desc: フロントエンド開発サーバーを起動
    dir: web
    cmds:
      - bun run dev

  # 開発サーバー起動（バックエンド）
  dev:backend:
    desc: バックエンド開発サーバーを起動
    dir: cmd/twitch-fax
    cmds:
      - air

  # Claude
  claude:
    desc: Claude起動
    cmds:
      - claude --dangerously-skip-permissions

  # twitch-faxプロセスを停止
  stop:
    desc: 実行中のtwitch-faxを停止
    cmds:
      - echo "twitch-faxプロセスを停止中..."
      - pkill -f twitch-fax || echo "実行中のtwitch-faxプロセスが見つかりませんでした"

  # ビルド済みアプリケーションを実行
  run:
    desc: ビルド済みのtwitch-faxを実行
    dir: dist
    cmds:
      - |
        if [ ! -f twitch-fax ]; then
          echo "エラー: dist/twitch-fax が見つかりません"
          echo "先に 'task build:all' でビルドしてください"
          exit 1
        fi
      - echo "twitch-faxを起動中..."
      - exec ./twitch-fax

  # テスト実行
  test:
    desc: 全テストを実行
    env:
      DRY_RUN_MODE: "true"
    cmds:
      - echo "テストを実行中..."
      - go test ./...

  # 配布用パッケージ作成
  package:
    desc: 配布用パッケージを作成
    deps: [build:all]
    cmds:
      - echo "配布用パッケージを作成中..."
      - mkdir -p dist-package
      - cp -r dist/* dist-package/
      - cp .env.template dist-package/
      - |
        if [ -f .env ]; then
          cp .env dist-package/.env
          echo ".envファイルをコピーしました"
        elif [ -f cmd/twitch-fax/.env ]; then
          cp cmd/twitch-fax/.env dist-package/.env
          echo "cmd/twitch-fax/.envファイルをコピーしました"
        fi
      - echo "パッケージ作成完了 → dist-package/"

  # systemdサービスインストール
  install:service:
    desc: systemdサービスをインストール（Linux）
    cmds:
      - |
        if [ ! -f scripts/install-service.sh ]; then
          echo "エラー: scripts/install-service.sh が見つかりません"
          exit 1
        fi
      - echo "systemdサービスをインストールします..."
      - bash scripts/install-service.sh {{.CLI_ARGS}}

  # systemdサービスアンインストール
  uninstall:service:
    desc: systemdサービスをアンインストール（Linux）
    vars:
      USERNAME:
        sh: echo ${1:-$USER}
    cmds:
      - echo "systemdサービスをアンインストールします..."
      - sudo systemctl stop twitch-fax@{{.USERNAME}}.service || true
      - sudo systemctl disable twitch-fax@{{.USERNAME}}.service || true
      - sudo rm -f /etc/systemd/system/twitch-fax@{{.USERNAME}}.service
      - sudo systemctl daemon-reload
      - echo "アンインストール完了"

  # サービス再起動
  service:restart:
    desc: systemdサービスを再起動
    vars:
      USERNAME:
        sh: echo ${1:-$USER}
    cmds:
      - echo "twitch-fax@{{.USERNAME}}.service を再起動します..."
      - sudo systemctl restart twitch-fax@{{.USERNAME}}.service
      - echo "再起動完了"
      - sudo systemctl status twitch-fax@{{.USERNAME}}.service --no-pager

  # サービス起動
  service:start:
    desc: systemdサービスを起動
    vars:
      USERNAME:
        sh: echo ${1:-$USER}
    cmds:
      - echo "twitch-fax@{{.USERNAME}}.service を起動します..."
      - sudo systemctl start twitch-fax@{{.USERNAME}}.service
      - echo "起動完了"
      - sudo systemctl status twitch-fax@{{.USERNAME}}.service --no-pager

  # サービス停止
  service:stop:
    desc: systemdサービスを停止
    vars:
      USERNAME:
        sh: echo ${1:-$USER}
    cmds:
      - echo "twitch-fax@{{.USERNAME}}.service を停止します..."
      - sudo systemctl stop twitch-fax@{{.USERNAME}}.service
      - echo "停止完了"

  # サービスステータス確認
  service:status:
    desc: systemdサービスの状態を確認
    vars:
      USERNAME:
        sh: echo ${1:-$USER}
    cmds:
      - sudo systemctl status twitch-fax@{{.USERNAME}}.service --no-pager

  # サービスログ確認
  service:logs:
    desc: systemdサービスのログを表示
    vars:
      USERNAME:
        sh: echo ${1:-$USER}
    cmds:
      - sudo journalctl -u twitch-fax@{{.USERNAME}}.service -f
