# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "../../"
testdata_dir = "testdata"
tmp_dir = "cmd/twitch-fax/tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -gcflags=\"all=-N -l\" -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
# --continueを外すとデバッガがアタッチするまで待機する。よってmain関数のデバッグも可能になる
# full_bin = "dlv --headless=true --listen=:41000 --api-version=2 --accept-multiclient exec ./tmp/main | zap-pretty"
full_bin = "dlv --headless=true --listen=:41000 --api-version=2 --accept-multiclient exec --continue ./tmp/main | zap-pretty"
include_dir = ["cmd/twitch-fax", "internal"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
