version: "3"

tasks:
  build:
    desc: Builds the application
    cmds:
      - echo "Building the project..."
      - go build -o ./dist/twitch-fax .

  test:
    desc: Test the  application
    cmds:
      - echo "Running tests..."
      - go test ./...

  dev:
    desc: Runs the application in development mode
    cmds:
      - echo "### Running... dev with zap-pretty"
      - air
